spring.application.name=mentory_proyect

# SQL Railway
spring.datasource.url=jdbc:mysql://root:aRVBHiJiHKKsAJFSyRZCpEQuzmnQbRsO@shuttle.proxy.rlwy.net:51895/railway
spring.datasource.username=root
spring.datasource.password=aRVBHiJiHKKsAJFSyRZCpEQuzmnQbRsO
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework=DEBUG
logging.level.com.cineuniverse.grupo1=DEBUG